version: '3.8'

services:
    frontend:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                - UID=${UID}
                - GID=${GID}
        image: vega-frontend

        volumes:
            - .:/app
        ports:
            - "8002:8002"
        env_file:
            - .env
        user: "${UID}:${GID}"